### ISSUE TITLE
Error: Unknown attribute request_creation_ipv4_offset from class IPConfig

### ISSUE THREAD

**Issue by annProg** [TeemIp/teemip-core-ip-mgmt#7]
When use REST/JSON Service, operation is `teemip/pick_ip_address_in_subnet`, will show error：

```json
{
  "code": 100,
  "message": "Error: Unknown attribute request_creation_ipv4_offset from class IPConfig"
}
```

grep code, IPConfig didn't define the attribute `request_creation_ipv4_offset`.
```bash
# find ./ -type f |xargs grep "request_creation_ipv4_offset"
./teemip-webservices/main.teemip-webservices.php:							$sParameter = ($sParentClass == 'IPv4Subnet') ? 'request_creation_ipv4_offset' : 'request_creation_ipv6_offset';
```

### Version info
- iTop 2.7.0-2
- TeemIp 2.6.1

**Comment by xtophe38** [comment]
There is actually a bug with that operation : it requires the module 'IP Request Mgmt' to be installed in order to properly work. Indeed, this extension is the place where the attribute 'request_creation_ip_offest" is defined. So, until it will be corrected in next TeemIp release, I suggest you to install the extension (available on GitHub, TeemIp's wiki or iTop's Hub), even if you don't use it. 

Alternative is to use the latest code for TeemIp's web services as correction has already been commited.

**Comment by annProg** [comment]
@xtophe38 thanks!
